/* Generated by Yosys 0.63 (git sha1 70a11c6bf0e8dd669f56c7da3587f78b405138e2, clang++ 17.0.0 -fPIC -O3) */

module \$paramod$90108688425d6ca9384d553077959b484f9ec825\gpio_ctrl (pclk, preset_n, psel, penable, pwrite, paddr, pwdata, pready, prdata, pslverr, gpio_i, gpio_o, gpio_oen, gpio_irq);
  input pclk;
  wire pclk;
  input preset_n;
  wire preset_n;
  input psel;
  wire psel;
  input penable;
  wire penable;
  input pwrite;
  wire pwrite;
  input [31:0] paddr;
  wire [31:0] paddr;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  output pready;
  reg pready;
  output [31:0] prdata;
  reg [31:0] prdata;
  output pslverr;
  reg pslverr;
  input [63:0] gpio_i;
  wire [63:0] gpio_i;
  output [63:0] gpio_o;
  reg [63:0] gpio_o;
  output [63:0] gpio_oen;
  reg [63:0] gpio_oen;
  output [63:0] gpio_irq;
  wire [63:0] gpio_irq;
  wire [63:0] _000_;
  wire [63:0] _001_;
  wire [63:0] _002_;
  wire [63:0] _003_;
  wire [63:0] _004_;
  wire [63:0] _005_;
  wire [63:0] _006_;
  wire [63:0] _007_;
  wire [63:0] _008_;
  wire [63:0] _009_;
  wire _010_;
  wire [63:0] _011_;
  wire [63:0] _012_;
  wire [63:0] _013_;
  wire [63:0] _014_;
  wire [63:0] _015_;
  wire [63:0] _016_;
  wire [63:0] _017_;
  wire [63:0] _018_;
  wire [63:0] _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [63:0] _072_;
  wire [63:0] _073_;
  wire [63:0] _074_;
  wire [63:0] _075_;
  wire [31:0] _076_;
  wire [31:0] _077_;
  wire [0:0] _078_;
  wire [0:0] _079_;
  wire [0:0] _080_;
  wire [0:0] _081_;
  wire [1:0] _082_;
  wire [1:0] _083_;
  wire [63:0] _084_;
  wire _085_;
  wire [1:0] _086_;
  wire _087_;
  wire [63:0] _088_;
  wire _089_;
  wire [63:0] _090_;
  wire [63:0] _091_;
  wire _092_;
  wire [63:0] _093_;
  wire [63:0] _094_;
  wire _095_;
  wire [63:0] _096_;
  wire [63:0] _097_;
  wire _098_;
  wire [63:0] _099_;
  wire [63:0] _100_;
  wire _101_;
  wire [63:0] _102_;
  wire [63:0] _103_;
  wire _104_;
  wire [63:0] _105_;
  wire [63:0] _106_;
  wire _107_;
  wire [63:0] _108_;
  wire [63:0] _109_;
  wire [63:0] _110_;
  wire [63:0] _111_;
  wire _112_;
  wire [63:0] _113_;
  wire _114_;
  wire [63:0] _115_;
  wire _116_;
  wire [63:0] _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire [31:0] _122_;
  wire _123_;
  wire [31:0] _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  reg [63:0] afrh_reg;
  reg [63:0] afrl_reg;
  reg [1:0] apb_state;
  wire [63:0] gpio_i_edge;
  reg [63:0] gpio_i_prev;
  wire [31:0] i;
  wire [63:0] idr_wire;
  reg [63:0] lckr_reg;
  reg [63:0] moder_reg;
  reg [63:0] odr_reg;
  reg [63:0] ospeedr_reg;
  reg [63:0] otyper_reg;
  wire [1:0] \pin_mode[0] ;
  wire [1:0] \pin_mode[10] ;
  wire [1:0] \pin_mode[11] ;
  wire [1:0] \pin_mode[12] ;
  wire [1:0] \pin_mode[13] ;
  wire [1:0] \pin_mode[14] ;
  wire [1:0] \pin_mode[15] ;
  wire [1:0] \pin_mode[1] ;
  wire [1:0] \pin_mode[2] ;
  wire [1:0] \pin_mode[3] ;
  wire [1:0] \pin_mode[4] ;
  wire [1:0] \pin_mode[5] ;
  wire [1:0] \pin_mode[6] ;
  wire [1:0] \pin_mode[7] ;
  wire [1:0] \pin_mode[8] ;
  wire [1:0] \pin_mode[9] ;
  reg [63:0] pupdr_reg;
  assign _009_ = gpio_o & _072_;
  assign _010_ = | { _116_, _107_, _104_, _101_, _098_, _095_, _092_, _089_, _020_ };
  assign _011_ = preset_n ? _002_ : gpio_o;
  assign _012_ = preset_n ? _004_ : moder_reg;
  assign _013_ = preset_n ? _007_ : otyper_reg;
  assign _014_ = preset_n ? _006_ : ospeedr_reg;
  assign _015_ = preset_n ? _008_ : pupdr_reg;
  assign _016_ = preset_n ? _005_ : odr_reg;
  assign _017_ = preset_n ? _003_ : lckr_reg;
  assign _018_ = preset_n ? _001_ : afrl_reg;
  assign _019_ = preset_n ? _000_ : afrh_reg;
  assign _021_ = ! pwdata[1:0];
  assign _022_ = pwdata[1:0] == 2'h3;
  assign _023_ = ! pwdata[3:2];
  assign _024_ = pwdata[3:2] == 2'h3;
  assign _025_ = ! pwdata[5:4];
  assign _026_ = pwdata[5:4] == 2'h3;
  assign _027_ = ! pwdata[7:6];
  assign _028_ = pwdata[7:6] == 2'h3;
  assign _029_ = ! pwdata[9:8];
  assign _030_ = pwdata[9:8] == 2'h3;
  assign _031_ = ! pwdata[11:10];
  assign _032_ = pwdata[11:10] == 2'h3;
  assign _033_ = ! pwdata[13:12];
  assign _034_ = pwdata[13:12] == 2'h3;
  assign _035_ = ! pwdata[15:14];
  assign _036_ = pwdata[15:14] == 2'h3;
  assign _037_ = ! pwdata[17:16];
  assign _038_ = pwdata[17:16] == 2'h3;
  assign _039_ = ! pwdata[19:18];
  assign _040_ = pwdata[19:18] == 2'h3;
  assign _041_ = ! pwdata[21:20];
  assign _042_ = pwdata[21:20] == 2'h3;
  assign _043_ = ! pwdata[23:22];
  assign _044_ = pwdata[23:22] == 2'h3;
  assign _045_ = ! pwdata[25:24];
  assign _046_ = pwdata[25:24] == 2'h3;
  assign _047_ = ! pwdata[27:26];
  assign _048_ = pwdata[27:26] == 2'h3;
  assign _049_ = ! pwdata[29:28];
  assign _050_ = pwdata[29:28] == 2'h3;
  assign _051_ = ! pwdata[31:30];
  assign _052_ = pwdata[31:30] == 2'h3;
  assign _053_ = pwrite && _020_;
  assign _054_ = psel && _055_;
  assign _055_ = ! penable;
  assign _056_ = _021_ || _022_;
  assign _057_ = _023_ || _024_;
  assign _058_ = _025_ || _026_;
  assign _059_ = _027_ || _028_;
  assign _060_ = _029_ || _030_;
  assign _061_ = _031_ || _032_;
  assign _062_ = _033_ || _034_;
  assign _063_ = _035_ || _036_;
  assign _064_ = _037_ || _038_;
  assign _065_ = _039_ || _040_;
  assign _066_ = _041_ || _042_;
  assign _067_ = _043_ || _044_;
  assign _068_ = _045_ || _046_;
  assign _069_ = _047_ || _048_;
  assign _070_ = _049_ || _050_;
  assign _071_ = _051_ || _052_;
  assign _072_ = ~ { 48'h000000000000, pwdata[31:16] };
  assign _073_ = gpio_o | pwdata[15:0];
  always @(posedge pclk)
    gpio_o <= _011_;
  always @(posedge pclk)
    moder_reg <= _012_;
  always @(posedge pclk)
    otyper_reg <= _013_;
  always @(posedge pclk)
    ospeedr_reg <= _014_;
  always @(posedge pclk)
    pupdr_reg <= _015_;
  always @(posedge pclk)
    odr_reg <= _016_;
  always @(posedge pclk)
    lckr_reg <= _017_;
  always @(posedge pclk)
    afrl_reg <= _018_;
  always @(posedge pclk)
    afrh_reg <= _019_;
  assign _074_[15] = _053_ ? _140_ : gpio_oen[15];
  assign _074_[14] = _053_ ? _139_ : gpio_oen[14];
  assign _074_[13] = _053_ ? _138_ : gpio_oen[13];
  assign _074_[12] = _053_ ? _137_ : gpio_oen[12];
  assign _074_[11] = _053_ ? _136_ : gpio_oen[11];
  assign _074_[10] = _053_ ? _135_ : gpio_oen[10];
  assign _074_[9] = _053_ ? _134_ : gpio_oen[9];
  assign _074_[8] = _053_ ? _133_ : gpio_oen[8];
  assign _074_[7] = _053_ ? _132_ : gpio_oen[7];
  assign _074_[6] = _053_ ? _131_ : gpio_oen[6];
  assign _074_[5] = _053_ ? _130_ : gpio_oen[5];
  assign _074_[4] = _053_ ? _129_ : gpio_oen[4];
  assign _074_[3] = _053_ ? _128_ : gpio_oen[3];
  assign _074_[2] = _053_ ? _127_ : gpio_oen[2];
  assign _074_[1] = _053_ ? _126_ : gpio_oen[1];
  assign _074_[0] = _053_ ? _125_ : gpio_oen[0];
  function [1:0] _230_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _230_ = b[1:0];
      2'b1?:
        _230_ = b[3:2];
      default:
        _230_ = a;
    endcase
  endfunction
  assign _082_ = _230_(apb_state, { _086_, 2'h0 }, { _087_, _085_ });
  assign _086_ = _054_ ? 2'h1 : apb_state;
  assign _088_ = _089_ ? { 32'h00000000, pwdata } : afrh_reg;
  assign _090_ = pwrite ? _088_ : afrh_reg;
  assign _000_ = _085_ ? _090_ : afrh_reg;
  assign _091_ = _092_ ? { 32'h00000000, pwdata } : afrl_reg;
  assign _093_ = pwrite ? _091_ : afrl_reg;
  assign _001_ = _085_ ? _093_ : afrl_reg;
  assign _094_ = _095_ ? { 32'h00000000, pwdata } : lckr_reg;
  assign _096_ = pwrite ? _094_ : lckr_reg;
  assign _003_ = _085_ ? _096_ : lckr_reg;
  assign _097_ = _098_ ? { 32'h00000000, pwdata } : odr_reg;
  assign _099_ = pwrite ? _097_ : odr_reg;
  assign _005_ = _085_ ? _099_ : odr_reg;
  assign _100_ = _101_ ? { 32'h00000000, pwdata } : pupdr_reg;
  assign _102_ = pwrite ? _100_ : pupdr_reg;
  assign _008_ = _085_ ? _102_ : pupdr_reg;
  assign _103_ = _104_ ? { 32'h00000000, pwdata } : ospeedr_reg;
  assign _105_ = pwrite ? _103_ : ospeedr_reg;
  assign _006_ = _085_ ? _105_ : ospeedr_reg;
  assign _106_ = _107_ ? { 32'h00000000, pwdata } : otyper_reg;
  assign _108_ = pwrite ? _106_ : otyper_reg;
  assign _007_ = _085_ ? _108_ : otyper_reg;
  assign _109_ = _020_ ? { 32'h00000000, pwdata } : moder_reg;
  assign _110_ = pwrite ? _109_ : moder_reg;
  assign _004_ = _085_ ? _110_ : moder_reg;
  assign _111_ = _112_ ? _073_ : gpio_o;
  assign _113_ = _114_ ? _009_ : _111_;
  function [63:0] _258_;
    input [63:0] a;
    input [127:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _258_ = b[63:0];
      2'b1?:
        _258_ = b[127:64];
      default:
        _258_ = a;
    endcase
  endfunction
  assign _115_ = _258_(gpio_o, { 48'h000000000000, pwdata[15:0], _113_ }, { _098_, _116_ });
  assign _117_ = pwrite ? _115_ : gpio_o;
  assign _002_ = _085_ ? _117_ : gpio_o;
  assign _118_ = _010_ ? pslverr : 1'h1;
  assign _116_ = paddr[7:2] == 6'h06;
  assign _119_ = pwrite ? _118_ : pslverr;
  function [0:0] _264_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _264_ = b[0:0];
      2'b1?:
        _264_ = b[1:1];
      default:
        _264_ = a;
    endcase
  endfunction
  assign _080_ = _264_(pslverr, { _120_, _119_ }, { _087_, _085_ });
  assign _120_ = _054_ ? 1'h0 : pslverr;
  function [0:0] _266_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _266_ = b[0:0];
      2'b1?:
        _266_ = b[1:1];
      default:
        _266_ = a;
    endcase
  endfunction
  assign _078_ = _266_(pready, { _121_, 1'h1 }, { _087_, _085_ });
  assign _121_ = _054_ ? 1'h0 : pready;
  assign _087_ = ! apb_state;
  function [31:0] _269_;
    input [31:0] a;
    input [287:0] b;
    input [8:0] s;
    casez (s) // synopsys parallel_case
      9'b????????1:
        _269_ = b[31:0];
      9'b???????1?:
        _269_ = b[63:32];
      9'b??????1??:
        _269_ = b[95:64];
      9'b?????1???:
        _269_ = b[127:96];
      9'b????1????:
        _269_ = b[159:128];
      9'b???1?????:
        _269_ = b[191:160];
      9'b??1??????:
        _269_ = b[223:192];
      9'b?1???????:
        _269_ = b[255:224];
      9'b1????????:
        _269_ = b[287:256];
      default:
        _269_ = a;
    endcase
  endfunction
  assign _122_ = _269_(32'd0, { moder_reg[31:0], otyper_reg[31:0], ospeedr_reg[31:0], pupdr_reg[31:0], gpio_i[31:0], 16'h0000, odr_reg[15:0], lckr_reg[31:0], afrl_reg[31:0], afrh_reg[31:0] }, { _020_, _107_, _104_, _101_, _123_, _098_, _095_, _092_, _089_ });
  assign _089_ = paddr[7:2] == 6'h09;
  assign _092_ = paddr[7:2] == 6'h08;
  assign _095_ = paddr[7:2] == 6'h07;
  assign _098_ = paddr[7:2] == 6'h05;
  assign _123_ = paddr[7:2] == 6'h04;
  assign _101_ = paddr[7:2] == 6'h03;
  assign _104_ = paddr[7:2] == 6'h02;
  assign _107_ = paddr[7:2] == 6'h01;
  assign _020_ = ! paddr[7:2];
  assign _124_ = pwrite ? prdata : _122_;
  assign _076_ = _085_ ? _124_ : prdata;
  assign _085_ = apb_state == 2'h1;
  assign _112_ = | pwdata[15:0];
  assign _114_ = | pwdata[31:16];
  always @(posedge pclk)
    gpio_oen <= _075_;
  assign _075_ = preset_n ? { gpio_oen[63:16], _074_[15:0] } : 64'h000000000000ffff;
  always @(posedge pclk)
    prdata <= _077_;
  assign _077_ = preset_n ? _076_ : 32'd0;
  always @(posedge pclk)
    pready <= _079_;
  assign _079_ = preset_n ? _078_ : 1'h0;
  always @(posedge pclk)
    pslverr <= _081_;
  assign _081_ = preset_n ? _080_ : 1'h0;
  always @(posedge pclk)
    apb_state <= _083_;
  assign _083_ = preset_n ? _082_ : 2'h0;
  always @(posedge pclk)
    gpio_i_prev <= _084_;
  assign _084_ = preset_n ? gpio_i : 64'h0000000000000000;
  assign _125_ = _056_ ? 1'h1 : 1'h0;
  assign _126_ = _057_ ? 1'h1 : 1'h0;
  assign _127_ = _058_ ? 1'h1 : 1'h0;
  assign _128_ = _059_ ? 1'h1 : 1'h0;
  assign _129_ = _060_ ? 1'h1 : 1'h0;
  assign _130_ = _061_ ? 1'h1 : 1'h0;
  assign _131_ = _062_ ? 1'h1 : 1'h0;
  assign _132_ = _063_ ? 1'h1 : 1'h0;
  assign _133_ = _064_ ? 1'h1 : 1'h0;
  assign _134_ = _065_ ? 1'h1 : 1'h0;
  assign _135_ = _066_ ? 1'h1 : 1'h0;
  assign _136_ = _067_ ? 1'h1 : 1'h0;
  assign _137_ = _068_ ? 1'h1 : 1'h0;
  assign _138_ = _069_ ? 1'h1 : 1'h0;
  assign _139_ = _070_ ? 1'h1 : 1'h0;
  assign _140_ = _071_ ? 1'h1 : 1'h0;
  assign gpio_irq = gpio_i ^ gpio_i_prev;
  assign _074_[63:16] = gpio_oen[63:16];
  assign \pin_mode[15]  = moder_reg[31:30];
  assign \pin_mode[14]  = moder_reg[29:28];
  assign \pin_mode[13]  = moder_reg[27:26];
  assign \pin_mode[12]  = moder_reg[25:24];
  assign \pin_mode[11]  = moder_reg[23:22];
  assign \pin_mode[10]  = moder_reg[21:20];
  assign \pin_mode[9]  = moder_reg[19:18];
  assign \pin_mode[8]  = moder_reg[17:16];
  assign \pin_mode[7]  = moder_reg[15:14];
  assign \pin_mode[6]  = moder_reg[13:12];
  assign \pin_mode[5]  = moder_reg[11:10];
  assign \pin_mode[4]  = moder_reg[9:8];
  assign \pin_mode[3]  = moder_reg[7:6];
  assign \pin_mode[2]  = moder_reg[5:4];
  assign \pin_mode[1]  = moder_reg[3:2];
  assign \pin_mode[0]  = moder_reg[1:0];
  assign i = 32'd16;
  assign gpio_i_edge = gpio_irq;
  assign idr_wire = gpio_i;
endmodule

module ahb2apb_bridge(hclk, hreset_n, haddr, hburst, hprot, hsize, htrans, hwrite, hwdata, hrdata, hready, hresp, hsel, paddr, psel, penable, pwrite, pwdata, prdata, pready, pslverr
);
  input hclk;
  wire hclk;
  input hreset_n;
  wire hreset_n;
  input [31:0] haddr;
  wire [31:0] haddr;
  input [2:0] hburst;
  wire [2:0] hburst;
  input [3:0] hprot;
  wire [3:0] hprot;
  input [2:0] hsize;
  wire [2:0] hsize;
  input [1:0] htrans;
  wire [1:0] htrans;
  input hwrite;
  wire hwrite;
  input [31:0] hwdata;
  wire [31:0] hwdata;
  output [31:0] hrdata;
  wire [31:0] hrdata;
  output hready;
  wire hready;
  output hresp;
  wire hresp;
  input hsel;
  wire hsel;
  output [31:0] paddr;
  wire [31:0] paddr;
  output psel;
  wire psel;
  output penable;
  wire penable;
  output pwrite;
  wire pwrite;
  output [31:0] pwdata;
  wire [31:0] pwdata;
  input [31:0] prdata;
  wire [31:0] prdata;
  input pready;
  wire pready;
  input pslverr;
  wire pslverr;
  wire [1:0] _00_;
  wire [1:0] _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [31:0] _17_;
  wire [31:0] _18_;
  wire [0:0] _19_;
  wire [0:0] _20_;
  wire [0:0] _21_;
  wire [0:0] _22_;
  wire [31:0] _23_;
  wire [31:0] _24_;
  wire [31:0] _25_;
  wire [31:0] _26_;
  wire [0:0] _27_;
  wire [0:0] _28_;
  wire [0:0] _29_;
  wire [0:0] _30_;
  wire [0:0] _31_;
  wire [0:0] _32_;
  wire [1:0] _33_;
  wire _34_;
  wire [1:0] _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire [31:0] _41_;
  wire [31:0] _42_;
  wire addr_valid;
  wire [31:0] apb_addr;
  reg [31:0] hrdata_reg;
  reg hready_reg;
  reg hresp_reg;
  reg [31:0] paddr_reg;
  reg penable_reg;
  reg psel_reg;
  reg [31:0] pwdata_reg;
  reg pwrite_reg;
  wire [1:0] state_next;
  reg [1:0] state_reg;
  assign _03_ = | { _38_, _37_ };
  assign _04_ = htrans == 2'h2;
  assign _06_ = haddr >= 32'd0;
  assign _07_ = hsel && _04_;
  assign _09_ = _12_ && hsel;
  assign _10_ = _09_ && _15_;
  assign _08_ = _05_ && pready;
  assign _11_ = _08_ && _13_;
  assign addr_valid = _06_ && _14_;
  assign _12_ = ! addr_valid;
  assign _13_ = ! pwrite_reg;
  assign _14_ = haddr < 32'd1048576;
  assign _15_ = | htrans;
  assign _16_ = ~ pready;
  assign _17_ = _11_ ? prdata : hrdata_reg;
  assign _34_ = _10_ ? 1'h1 : 1'h0;
  assign _19_ = _08_ ? pslverr : _34_;
  function [0:0] _60_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _60_ = b[0:0];
      3'b?1?:
        _60_ = b[1:1];
      3'b1??:
        _60_ = b[2:2];
      default:
        _60_ = a;
    endcase
  endfunction
  assign _21_ = _60_(1'hx, { 2'h2, _16_ }, { _38_, _37_, _36_ });
  function [0:0] _61_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _61_ = b[0:0];
      2'b1?:
        _61_ = b[1:1];
      default:
        _61_ = a;
    endcase
  endfunction
  assign _31_ = _61_(1'hx, { 1'h0, _39_ }, { _03_, _36_ });
  assign _39_ = pready ? 1'h0 : 1'h1;
  function [0:0] _63_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _63_ = b[0:0];
      3'b?1?:
        _63_ = b[1:1];
      3'b1??:
        _63_ = b[2:2];
      default:
        _63_ = a;
    endcase
  endfunction
  assign _29_ = _63_(1'hx, { 2'h1, _39_ }, { _38_, _37_, _36_ });
  assign _36_ = | { _35_[1], _05_ };
  assign _40_ = _07_ ? hwrite : pwrite_reg;
  assign _27_ = _38_ ? _40_ : pwrite_reg;
  assign _41_ = _07_ ? hwdata : pwdata_reg;
  assign _25_ = _38_ ? _41_ : pwdata_reg;
  assign _42_ = _07_ ? haddr : paddr_reg;
  assign _23_ = _38_ ? _42_ : paddr_reg;
  assign _02_ = pready ? 2'h0 : state_reg;
  assign _01_ = pready ? 2'h0 : 2'h3;
  assign _00_ = _07_ ? 2'h1 : state_reg;
  function [1:0] _74_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _74_ = b[1:0];
      4'b??1?:
        _74_ = b[3:2];
      4'b?1??:
        _74_ = b[5:4];
      4'b1???:
        _74_ = b[7:6];
      default:
        _74_ = a;
    endcase
  endfunction
  assign state_next = _74_(2'hx, { _00_, 2'h2, _01_, _02_ }, { _38_, _37_, _05_, _35_[1] });
  assign _35_[1] = state_reg == 2'h3;
  assign _05_ = state_reg == 2'h2;
  assign _37_ = state_reg == 2'h1;
  assign _38_ = ! state_reg;
  always @(posedge hclk)
    hrdata_reg <= _18_;
  assign _18_ = hreset_n ? _17_ : 32'd0;
  always @(posedge hclk)
    hresp_reg <= _20_;
  assign _20_ = hreset_n ? _19_ : 1'h0;
  always @(posedge hclk)
    hready_reg <= _22_;
  assign _22_ = hreset_n ? _21_ : 1'h1;
  always @(posedge hclk)
    paddr_reg <= _24_;
  assign _24_ = hreset_n ? _23_ : 32'd0;
  always @(posedge hclk)
    pwdata_reg <= _26_;
  assign _26_ = hreset_n ? _25_ : 32'd0;
  always @(posedge hclk)
    pwrite_reg <= _28_;
  assign _28_ = hreset_n ? _27_ : 1'h0;
  always @(posedge hclk)
    psel_reg <= _30_;
  assign _30_ = hreset_n ? _29_ : 1'h0;
  always @(posedge hclk)
    penable_reg <= _32_;
  assign _32_ = hreset_n ? _31_ : 1'h0;
  always @(posedge hclk)
    state_reg <= _33_;
  assign _33_ = hreset_n ? state_next : 2'h0;
  assign _35_[0] = _05_;
  assign apb_addr = haddr;
  assign pwdata = pwdata_reg;
  assign pwrite = pwrite_reg;
  assign penable = penable_reg;
  assign psel = psel_reg;
  assign paddr = paddr_reg;
  assign hresp = hresp_reg;
  assign hready = hready_reg;
  assign hrdata = hrdata_reg;
endmodule

module ahb_matrix(hclk, hreset_n, haddr_m, hburst_m, hprot_m, hsize_m, htrans_m, hwrite_m, hwdata_m, hrdata_m, hready_m, hresp_m, haddr_s0, hburst_s0, hprot_s0, hsize_s0, htrans_s0, hwrite_s0, hwdata_s0, hrdata_s0, hready_s0
, hresp_s0, hsel_s0, haddr_s1, hburst_s1, hprot_s1, hsize_s1, htrans_s1, hwrite_s1, hwdata_s1, hrdata_s1, hready_s1, hresp_s1, hsel_s1, haddr_s2, hburst_s2, hprot_s2, hsize_s2, htrans_s2, hwrite_s2, hwdata_s2, hrdata_s2
, hready_s2, hresp_s2, hsel_s2);
  input hclk;
  wire hclk;
  input hreset_n;
  wire hreset_n;
  input [31:0] haddr_m;
  wire [31:0] haddr_m;
  input [2:0] hburst_m;
  wire [2:0] hburst_m;
  input [3:0] hprot_m;
  wire [3:0] hprot_m;
  input [2:0] hsize_m;
  wire [2:0] hsize_m;
  input [1:0] htrans_m;
  wire [1:0] htrans_m;
  input hwrite_m;
  wire hwrite_m;
  input [31:0] hwdata_m;
  wire [31:0] hwdata_m;
  output [31:0] hrdata_m;
  wire [31:0] hrdata_m;
  output hready_m;
  wire hready_m;
  output hresp_m;
  wire hresp_m;
  output [31:0] haddr_s0;
  wire [31:0] haddr_s0;
  output [2:0] hburst_s0;
  wire [2:0] hburst_s0;
  output [3:0] hprot_s0;
  wire [3:0] hprot_s0;
  output [2:0] hsize_s0;
  wire [2:0] hsize_s0;
  output [1:0] htrans_s0;
  wire [1:0] htrans_s0;
  output hwrite_s0;
  wire hwrite_s0;
  output [31:0] hwdata_s0;
  wire [31:0] hwdata_s0;
  input [31:0] hrdata_s0;
  wire [31:0] hrdata_s0;
  input hready_s0;
  wire hready_s0;
  input hresp_s0;
  wire hresp_s0;
  output hsel_s0;
  wire hsel_s0;
  output [31:0] haddr_s1;
  wire [31:0] haddr_s1;
  output [2:0] hburst_s1;
  wire [2:0] hburst_s1;
  output [3:0] hprot_s1;
  wire [3:0] hprot_s1;
  output [2:0] hsize_s1;
  wire [2:0] hsize_s1;
  output [1:0] htrans_s1;
  wire [1:0] htrans_s1;
  output hwrite_s1;
  wire hwrite_s1;
  output [31:0] hwdata_s1;
  wire [31:0] hwdata_s1;
  input [31:0] hrdata_s1;
  wire [31:0] hrdata_s1;
  input hready_s1;
  wire hready_s1;
  input hresp_s1;
  wire hresp_s1;
  output hsel_s1;
  wire hsel_s1;
  output [31:0] haddr_s2;
  wire [31:0] haddr_s2;
  output [2:0] hburst_s2;
  wire [2:0] hburst_s2;
  output [3:0] hprot_s2;
  wire [3:0] hprot_s2;
  output [2:0] hsize_s2;
  wire [2:0] hsize_s2;
  output [1:0] htrans_s2;
  wire [1:0] htrans_s2;
  output hwrite_s2;
  wire hwrite_s2;
  output [31:0] hwdata_s2;
  wire [31:0] hwdata_s2;
  input [31:0] hrdata_s2;
  wire [31:0] hrdata_s2;
  input hready_s2;
  wire hready_s2;
  input hresp_s2;
  wire hresp_s2;
  output hsel_s2;
  wire hsel_s2;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [31:0] _15_;
  wire [31:0] _16_;
  wire [0:0] _17_;
  wire [0:0] _18_;
  wire [0:0] _19_;
  wire [0:0] _20_;
  wire [31:0] _21_;
  wire _22_;
  wire _23_;
  wire [31:0] _24_;
  wire [31:0] _25_;
  reg [31:0] hrdata_reg;
  reg hready_q;
  reg hresp_reg;
  wire slave_ready;
  wire slave_resp;
  wire [1:0] slave_sel;
  wire slave_sel_0;
  wire slave_sel_1;
  wire slave_sel_2;
  assign _00_ = ! htrans_m;
  assign _01_ = haddr_m >= 32'd0;
  assign _02_ = haddr_m >= 32'd536870912;
  assign _03_ = haddr_m >= 32'd1073741824;
  assign _04_ = slave_sel[0] && hready_s0;
  assign _05_ = slave_sel[1] && hready_s1;
  assign _06_ = slave_sel[0] && hresp_s0;
  assign _07_ = slave_sel[1] && hresp_s1;
  assign _08_ = hready_q && _13_;
  assign _09_ = _08_ && _14_;
  assign slave_sel_0 = _01_ && _10_;
  assign slave_sel_1 = _02_ && _11_;
  assign slave_sel_2 = _03_ && _12_;
  assign slave_ready = _04_ || _05_;
  assign slave_resp = _06_ || _07_;
  assign _10_ = haddr_m < 32'd524288;
  assign _11_ = haddr_m < 32'd537001984;
  assign _12_ = haddr_m < 32'd1074790400;
  assign _13_ = | htrans_m;
  assign _14_ = htrans_m != 2'h1;
  function [31:0] _46_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _46_ = b[31:0];
      2'b1?:
        _46_ = b[63:32];
      default:
        _46_ = a;
    endcase
  endfunction
  assign _21_ = _46_(32'd0, { hrdata_s0, hrdata_s1 }, { _23_, _22_ });
  assign _22_ = slave_sel == 2'h2;
  assign _23_ = slave_sel == 2'h1;
  assign _15_ = _09_ ? _21_ : hrdata_reg;
  assign _17_ = _13_ ? slave_resp : hresp_reg;
  assign _19_ = _00_ ? 1'h1 : slave_ready;
  assign _24_ = haddr_m - 32'd536870912;
  assign _25_ = haddr_m - 32'd1073741824;
  always @(posedge hclk)
    hrdata_reg <= _16_;
  assign _16_ = hreset_n ? _15_ : 32'd0;
  always @(posedge hclk)
    hresp_reg <= _18_;
  assign _18_ = hreset_n ? _17_ : 1'h0;
  always @(posedge hclk)
    hready_q <= _20_;
  assign _20_ = hreset_n ? _19_ : 1'h1;
  assign haddr_s0 = slave_sel_0 ? haddr_m : 32'd0;
  assign haddr_s1 = slave_sel_1 ? _24_ : 32'd0;
  assign haddr_s2 = slave_sel_2 ? _25_ : 32'd0;
  assign htrans_s0 = slave_sel_0 ? htrans_m : 2'h0;
  assign htrans_s1 = slave_sel_1 ? htrans_m : 2'h0;
  assign htrans_s2 = slave_sel_2 ? htrans_m : 2'h0;
  assign hsel_s2 = slave_sel_2;
  assign hwdata_s2 = hwdata_m;
  assign hwrite_s2 = hwrite_m;
  assign hsize_s2 = hsize_m;
  assign hprot_s2 = hprot_m;
  assign hburst_s2 = hburst_m;
  assign hsel_s1 = slave_sel_1;
  assign hwdata_s1 = hwdata_m;
  assign hwrite_s1 = hwrite_m;
  assign hsize_s1 = hsize_m;
  assign hprot_s1 = hprot_m;
  assign hburst_s1 = hburst_m;
  assign hsel_s0 = slave_sel_0;
  assign hwdata_s0 = hwdata_m;
  assign hwrite_s0 = hwrite_m;
  assign hsize_s0 = hsize_m;
  assign hprot_s0 = hprot_m;
  assign hburst_s0 = hburst_m;
  assign hresp_m = hresp_reg;
  assign hready_m = hready_q;
  assign hrdata_m = hrdata_reg;
endmodule

module apb_peripherals(PCLK, PRESETn, PSEL, PENABLE, PWRITE, PADDR, PWDATA, PREADY, PRDATA, irq, gpio_i, gpio_o, gpio_oen, uart0_rx, uart0_tx, uart1_rx, uart1_tx);
  input PCLK;
  wire PCLK;
  input PRESETn;
  wire PRESETn;
  input PSEL;
  wire PSEL;
  input PENABLE;
  wire PENABLE;
  input PWRITE;
  wire PWRITE;
  input [31:0] PADDR;
  wire [31:0] PADDR;
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  output PREADY;
  wire PREADY;
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  output [31:0] irq;
  wire [31:0] irq;
  input [63:0] gpio_i;
  wire [63:0] gpio_i;
  output [63:0] gpio_o;
  wire [63:0] gpio_o;
  output [63:0] gpio_oen;
  wire [63:0] gpio_oen;
  input uart0_rx;
  wire uart0_rx;
  output uart0_tx;
  wire uart0_tx;
  input uart1_rx;
  wire uart1_rx;
  output uart1_tx;
  wire uart1_tx;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [31:0] apb_addr_offset;
  wire [63:0] gpio_irq;
  wire gpio_psel;
  wire [31:0] gpio_rdata;
  wire gpio_ready;
  wire uart0_psel;
  wire [31:0] uart0_rdata;
  wire uart0_ready;
  wire uart1_psel;
  wire [31:0] uart1_rdata;
  wire uart1_ready;
  wire [31:0] uart_irq;
  assign gpio_psel = PSEL & _00_;
  assign uart0_psel = PSEL & _01_;
  assign _00_ = ! PADDR[31:12];
  assign _01_ = PADDR[31:12] == 12'h001;
  assign _02_ = gpio_ready | uart0_ready;
  assign PREADY = _02_ | uart1_ready;
  assign irq[0] = | gpio_irq[15:0];
  assign irq[1] = | gpio_irq[31:16];
  assign irq[2] = | gpio_irq[47:32];
  assign irq[3] = | gpio_irq[63:48];
  assign _03_ = uart0_psel ? uart0_rdata : uart1_rdata;
  assign PRDATA = gpio_psel ? gpio_rdata : _03_;
  \$paramod$90108688425d6ca9384d553077959b484f9ec825\gpio_ctrl  u_gpio_ctrl (
    .gpio_i(gpio_i),
    .gpio_irq(gpio_irq),
    .gpio_o(gpio_o),
    .gpio_oen(gpio_oen),
    .paddr(PADDR),
    .pclk(PCLK),
    .penable(PENABLE),
    .prdata(gpio_rdata),
    .pready(gpio_ready),
    .preset_n(PRESETn),
    .psel(gpio_psel),
    .pwdata(PWDATA),
    .pwrite(PWRITE)
  );
  uart_simple u_uart0 (
    .irq(uart_irq[0]),
    .paddr(PADDR),
    .pclk(PCLK),
    .penable(PENABLE),
    .prdata(uart0_rdata),
    .pready(uart0_ready),
    .preset_n(PRESETn),
    .psel(uart0_psel),
    .pwdata(PWDATA),
    .pwrite(PWRITE),
    .rx(uart0_rx),
    .tx(uart0_tx)
  );
  uart_simple u_uart1 (
    .irq(uart_irq[1]),
    .paddr(PADDR),
    .pclk(PCLK),
    .penable(PENABLE),
    .prdata(uart1_rdata),
    .pready(uart1_ready),
    .preset_n(PRESETn),
    .psel(uart0_psel),
    .pwdata(PWDATA),
    .pwrite(PWRITE),
    .rx(uart1_rx),
    .tx(uart1_tx)
  );
  assign uart1_psel = uart0_psel;
  assign apb_addr_offset = PADDR;
  assign irq[31:4] = { 26'h0000000, uart_irq[1:0] };
endmodule

module clk_gen(osc_clk, rst_n, hclk, pclk, hreset_n, preset_n, clk_locked, rst_active);
  input osc_clk;
  wire osc_clk;
  input rst_n;
  wire rst_n;
  output hclk;
  wire hclk;
  output pclk;
  wire pclk;
  output hreset_n;
  wire hreset_n;
  output preset_n;
  wire preset_n;
  output clk_locked;
  wire clk_locked;
  output rst_active;
  wire rst_active;
  wire _00_;
  wire [1:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [0:0] _04_;
  wire [0:0] _05_;
  wire [0:0] _06_;
  wire [0:0] _07_;
  wire [0:0] _08_;
  reg hclk_reg;
  reg pclk_reg;
  reg pll_locked_reg;
  reg [1:0] preset_sync;
  reg [3:0] rst_sync_reg;
  assign rst_active = ! hreset_n;
  assign _04_ = ~ hclk_reg;
  assign _00_ = ~ pclk_reg;
  assign _02_ = pll_locked_reg ? { rst_sync_reg[2:0], 1'h1 } : 4'h0;
  assign hreset_n = & rst_sync_reg;
  always @(posedge pclk_reg)
    preset_sync <= _01_;
  assign _01_ = rst_n ? { preset_sync[0], hreset_n } : 2'h0;
  always @(posedge hclk_reg)
    rst_sync_reg <= _03_;
  assign _03_ = rst_n ? _02_ : 4'h0;
  always @(posedge osc_clk)
    hclk_reg <= _05_;
  assign _05_ = rst_n ? _04_ : 1'h0;
  always @(posedge osc_clk)
    pclk_reg <= _07_;
  assign _07_ = rst_n ? _06_ : 1'h0;
  always @(posedge osc_clk)
    pll_locked_reg <= _08_;
  assign _08_ = rst_n ? 1'h1 : 1'h0;
  assign _06_ = hclk_reg ? pclk_reg : _00_;
  assign clk_locked = pll_locked_reg;
  assign preset_n = preset_sync[1];
  assign pclk = pclk_reg;
  assign hclk = hclk_reg;
endmodule

module cortex_m3_soc(clk, rst_n, osc_clk, tck, tms, tdi, tdo, ntrst, ext_irq, gpio_i, gpio_o, gpio_oen, uart0_rx, uart0_tx, uart1_rx, uart1_tx, flash_addr_o, flash_data_io, flash_ce_n, flash_oe_n);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input osc_clk;
  wire osc_clk;
  input tck;
  wire tck;
  input tms;
  wire tms;
  input tdi;
  wire tdi;
  output tdo;
  wire tdo;
  input ntrst;
  wire ntrst;
  input [31:0] ext_irq;
  wire [31:0] ext_irq;
  input [63:0] gpio_i;
  wire [63:0] gpio_i;
  output [63:0] gpio_o;
  wire [63:0] gpio_o;
  output [63:0] gpio_oen;
  wire [63:0] gpio_oen;
  input uart0_rx;
  wire uart0_rx;
  output uart0_tx;
  wire uart0_tx;
  input uart1_rx;
  wire uart1_rx;
  output uart1_tx;
  wire uart1_tx;
  output [19:0] flash_addr_o;
  wire [19:0] flash_addr_o;
  inout [31:0] flash_data_io;
  wire [31:0] flash_data_io;
  output flash_ce_n;
  wire flash_ce_n;
  output flash_oe_n;
  wire flash_oe_n;
  wire [31:0] bridge_haddr;
  wire [31:0] bridge_hrdata;
  wire bridge_hready;
  wire bridge_hresp;
  wire bridge_hsel;
  wire [31:0] bridge_hwdata;
  wire bridge_hwrite;
  wire [31:0] flash_haddr;
  wire [31:0] flash_hrdata;
  wire flash_hready;
  wire flash_hresp;
  wire flash_hsel;
  wire [31:0] flash_hwdata;
  wire flash_hwrite;
  wire [31:0] haddr;
  wire [2:0] hburst;
  wire hclk;
  wire hmastlock;
  wire [3:0] hprot;
  wire [31:0] hrdata;
  wire hready;
  wire hreset_n;
  wire hresp;
  wire [2:0] hsize;
  wire [1:0] htrans;
  wire [31:0] hwdata;
  wire hwrite;
  wire [31:0] irq;
  wire [31:0] paddr;
  wire pclk;
  wire penable;
  wire [31:0] prdata;
  wire pready;
  wire preset_n;
  wire psel;
  wire pslverr;
  wire [31:0] pwdata;
  wire pwrite;
  wire [31:0] sram_haddr;
  wire [31:0] sram_hrdata;
  wire sram_hready;
  wire sram_hresp;
  wire sram_hsel;
  wire [31:0] sram_hwdata;
  wire sram_hwrite;
  ahb2apb_bridge u_ahb2apb (
    .haddr(bridge_haddr),
    .hburst(hburst),
    .hclk(hclk),
    .hprot(hprot),
    .hrdata(bridge_hrdata),
    .hready(bridge_hready),
    .hreset_n(hreset_n),
    .hresp(bridge_hresp),
    .hsel(bridge_hsel),
    .hsize(hsize),
    .htrans(htrans),
    .hwdata(bridge_hwdata),
    .hwrite(bridge_hwrite),
    .paddr(paddr),
    .penable(penable),
    .prdata(prdata),
    .pready(pready),
    .psel(psel),
    .pslverr(pslverr),
    .pwdata(pwdata),
    .pwrite(pwrite)
  );
  ahb_matrix u_ahb_matrix (
    .haddr_m(haddr),
    .haddr_s0(flash_haddr),
    .haddr_s1(sram_haddr),
    .haddr_s2(bridge_haddr),
    .hburst_m(hburst),
    .hburst_s0(hburst),
    .hburst_s1(hburst),
    .hburst_s2(hburst),
    .hclk(hclk),
    .hprot_m(hprot),
    .hprot_s0(hprot),
    .hprot_s1(hprot),
    .hprot_s2(hprot),
    .hrdata_m(hrdata),
    .hrdata_s0(flash_hrdata),
    .hrdata_s1(sram_hrdata),
    .hrdata_s2(bridge_hrdata),
    .hready_m(hready),
    .hready_s0(flash_hready),
    .hready_s1(sram_hready),
    .hready_s2(bridge_hready),
    .hreset_n(hreset_n),
    .hresp_m(hresp),
    .hresp_s0(flash_hresp),
    .hresp_s1(sram_hresp),
    .hresp_s2(bridge_hresp),
    .hsel_s0(flash_hsel),
    .hsel_s1(sram_hsel),
    .hsel_s2(bridge_hsel),
    .hsize_m(hsize),
    .hsize_s0(hsize),
    .hsize_s1(hsize),
    .hsize_s2(hsize),
    .htrans_m(htrans),
    .htrans_s0(htrans),
    .htrans_s1(htrans),
    .htrans_s2(htrans),
    .hwdata_m(hwdata),
    .hwdata_s0(flash_hwdata),
    .hwdata_s1(sram_hwdata),
    .hwdata_s2(bridge_hwdata),
    .hwrite_m(hwrite),
    .hwrite_s0(flash_hwrite),
    .hwrite_s1(sram_hwrite),
    .hwrite_s2(bridge_hwrite)
  );
  apb_peripherals u_apb_peripherals (
    .PADDR(paddr),
    .PCLK(pclk),
    .PENABLE(penable),
    .PRDATA(prdata),
    .PREADY(pready),
    .PRESETn(preset_n),
    .PSEL(psel),
    .PWDATA(pwdata),
    .PWRITE(pwrite),
    .gpio_i(gpio_i),
    .gpio_o(gpio_o),
    .gpio_oen(gpio_oen),
    .irq(irq),
    .uart0_rx(uart0_rx),
    .uart0_tx(uart0_tx),
    .uart1_rx(uart1_rx),
    .uart1_tx(uart1_tx)
  );
  clk_gen u_clk_gen (
    .hclk(hclk),
    .hreset_n(hreset_n),
    .osc_clk(osc_clk),
    .pclk(pclk),
    .preset_n(preset_n),
    .rst_n(rst_n)
  );
  cortex_m3 u_cpu (
    .HADDR(haddr),
    .HBURST(hburst),
    .HCLK(hclk),
    .HMASTLOCK(hmastlock),
    .HPROT(hprot),
    .HRDATA(hrdata),
    .HREADY(hready),
    .HRESETn(hreset_n),
    .HRESP(hresp),
    .HSIZE(hsize),
    .HTRANS(htrans),
    .HWDATA(hwdata),
    .HWRITE(hwrite),
    .IRQ(irq),
    .NMI(1'h0),
    .TCK(tck),
    .TDI(tdi),
    .TDO(tdo),
    .TMS(tms),
    .nTRST(ntrst)
  );
  flash_ctrl u_flash_ctrl (
    .flash_addr_o(flash_addr_o),
    .flash_ce_n(flash_ce_n),
    .flash_data_io(flash_data_io),
    .flash_oe_n(flash_oe_n),
    .haddr(flash_haddr),
    .hburst(hburst),
    .hclk(hclk),
    .hprot(hprot),
    .hrdata(flash_hrdata),
    .hready(flash_hready),
    .hreset_n(hreset_n),
    .hresp(flash_hresp),
    .hsel(flash_hsel),
    .hsize(hsize),
    .htrans(htrans),
    .hwdata(flash_hwdata),
    .hwrite(flash_hwrite)
  );
  sram_ctrl u_sram_ctrl (
    .haddr(sram_haddr),
    .hburst(hburst),
    .hclk(hclk),
    .hprot(hprot),
    .hrdata(sram_hrdata),
    .hready(sram_hready),
    .hreset_n(hreset_n),
    .hresp(sram_hresp),
    .hsel(sram_hsel),
    .hsize(hsize),
    .htrans(htrans),
    .hwdata(sram_hwdata),
    .hwrite(sram_hwrite)
  );
endmodule

module sram_ctrl(hclk, hreset_n, haddr, hburst, hprot, hsize, htrans, hwrite, hwdata, hrdata, hready, hresp, hsel, itcm_addr_o, itcm_wdata_o, itcm_rdata_i, itcm_be_o, itcm_ce_o, itcm_we_o, dtcm_addr_o, dtcm_wdata_o
, dtcm_rdata_i, dtcm_be_o, dtcm_ce_o, dtcm_we_o);
  input hclk;
  wire hclk;
  input hreset_n;
  wire hreset_n;
  input [31:0] haddr;
  wire [31:0] haddr;
  input [2:0] hburst;
  wire [2:0] hburst;
  input [3:0] hprot;
  wire [3:0] hprot;
  input [2:0] hsize;
  wire [2:0] hsize;
  input [1:0] htrans;
  wire [1:0] htrans;
  input hwrite;
  wire hwrite;
  input [31:0] hwdata;
  wire [31:0] hwdata;
  output [31:0] hrdata;
  wire [31:0] hrdata;
  output hready;
  wire hready;
  output hresp;
  wire hresp;
  input hsel;
  wire hsel;
  output [15:0] itcm_addr_o;
  wire [15:0] itcm_addr_o;
  output [31:0] itcm_wdata_o;
  wire [31:0] itcm_wdata_o;
  input [31:0] itcm_rdata_i;
  wire [31:0] itcm_rdata_i;
  output [3:0] itcm_be_o;
  wire [3:0] itcm_be_o;
  output itcm_ce_o;
  wire itcm_ce_o;
  output itcm_we_o;
  wire itcm_we_o;
  output [15:0] dtcm_addr_o;
  wire [15:0] dtcm_addr_o;
  output [31:0] dtcm_wdata_o;
  wire [31:0] dtcm_wdata_o;
  input [31:0] dtcm_rdata_i;
  wire [31:0] dtcm_rdata_i;
  output [3:0] dtcm_be_o;
  wire [3:0] dtcm_be_o;
  output dtcm_ce_o;
  wire dtcm_ce_o;
  output dtcm_we_o;
  wire dtcm_we_o;
  wire [3:0] _000_;
  wire [31:0] _001_;
  wire [3:0] _002_;
  wire [31:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire [31:0] _024_;
  wire [31:0] _025_;
  wire [0:0] _026_;
  wire [0:0] _027_;
  wire [0:0] _028_;
  wire [0:0] _029_;
  wire [3:0] _030_;
  wire [3:0] _031_;
  wire [31:0] _032_;
  wire [31:0] _033_;
  wire [15:0] _034_;
  wire [15:0] _035_;
  wire [0:0] _036_;
  wire [0:0] _037_;
  wire [0:0] _038_;
  wire [0:0] _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire [31:0] _047_;
  wire [31:0] _048_;
  reg access_itcm;
  reg [15:0] addr_reg;
  wire [3:0] be_next;
  reg [3:0] be_reg;
  wire [16:0] byte_addr;
  wire [31:0] hrdata_aligned;
  reg [31:0] hrdata_reg;
  reg hready_reg;
  reg hresp_reg;
  wire is_dtcm_access;
  wire is_itcm_access;
  reg [31:0] wdata_reg;
  reg we_reg;
  wire [15:0] word_addr;
  assign _004_ = haddr >= 17'h10000;
  assign _006_ = _005_ && _023_;
  assign _007_ = hsel && _017_;
  assign _008_ = _007_ && _022_;
  assign _009_ = _008_ && _023_;
  assign _005_ = hsel && _022_;
  assign _010_ = _005_ && _018_;
  assign _011_ = _010_ && _019_;
  assign _012_ = hsel && access_itcm;
  assign itcm_ce_o = _012_ && _022_;
  assign itcm_we_o = we_reg && access_itcm;
  assign _013_ = _020_ && is_dtcm_access;
  assign _014_ = hsel && _020_;
  assign _015_ = _014_ && is_dtcm_access;
  assign dtcm_ce_o = _015_ && _022_;
  assign _016_ = we_reg && _020_;
  assign dtcm_we_o = _016_ && is_dtcm_access;
  assign is_dtcm_access = _004_ && _021_;
  assign _017_ = ! hwrite;
  assign _018_ = ! is_itcm_access;
  assign _019_ = ! is_dtcm_access;
  assign _020_ = ! access_itcm;
  assign is_itcm_access = haddr < 17'h10000;
  assign _021_ = haddr < 17'h00000;
  assign _023_ = htrans != 2'h1;
  assign _022_ = | htrans;
  assign _003_ = haddr[1] ? { hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31:16] } : { hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15:0] };
  function [31:0] _076_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _076_ = b[31:0];
      4'b??1?:
        _076_ = b[63:32];
      4'b?1??:
        _076_ = b[95:64];
      4'b1???:
        _076_ = b[127:96];
      default:
        _076_ = a;
    endcase
  endfunction
  assign _001_ = _076_(32'hxxxxxxxx, { hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7], hrdata_reg[7:0], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15], hrdata_reg[15:8], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23], hrdata_reg[23:16], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31], hrdata_reg[31:24] }, { _044_, _043_, _042_, _041_ });
  function [31:0] _077_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _077_ = b[31:0];
      2'b1?:
        _077_ = b[63:32];
      default:
        _077_ = a;
    endcase
  endfunction
  assign hrdata = _077_(hrdata_reg, { _001_, _003_ }, { _045_, _040_ });
  assign _028_ = _011_ ? 1'h1 : 1'h0;
  assign _046_ = hwrite ? 1'h1 : 1'h0;
  assign _026_ = _006_ ? _046_ : 1'h1;
  assign _038_ = _006_ ? is_itcm_access : access_itcm;
  assign _036_ = _006_ ? hwrite : we_reg;
  assign _034_ = _006_ ? haddr[16:1] : addr_reg;
  assign _032_ = _006_ ? hwdata : wdata_reg;
  assign _030_ = _006_ ? be_next : be_reg;
  assign _047_ = is_dtcm_access ? dtcm_rdata_i : hrdata_reg;
  assign _048_ = is_itcm_access ? itcm_rdata_i : _047_;
  assign _024_ = _009_ ? _048_ : hrdata_reg;
  assign _002_ = haddr[1] ? 4'hc : 4'h3;
  function [3:0] _090_;
    input [3:0] a;
    input [15:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _090_ = b[3:0];
      4'b??1?:
        _090_ = b[7:4];
      4'b?1??:
        _090_ = b[11:8];
      4'b1???:
        _090_ = b[15:12];
      default:
        _090_ = a;
    endcase
  endfunction
  assign _000_ = _090_(4'hx, 16'h1248, { _044_, _043_, _042_, _041_ });
  assign _041_ = haddr[1:0] == 2'h3;
  assign _042_ = haddr[1:0] == 2'h2;
  assign _043_ = haddr[1:0] == 2'h1;
  assign _044_ = ! haddr[1:0];
  function [3:0] _095_;
    input [3:0] a;
    input [7:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _095_ = b[3:0];
      2'b1?:
        _095_ = b[7:4];
      default:
        _095_ = a;
    endcase
  endfunction
  assign be_next = _095_(4'hf, { _000_, _002_ }, { _045_, _040_ });
  assign _040_ = hsize == 3'h1;
  assign _045_ = ! hsize;
  always @(posedge hclk)
    hrdata_reg <= _025_;
  assign _025_ = hreset_n ? _024_ : 32'd0;
  always @(posedge hclk)
    hready_reg <= _027_;
  assign _027_ = hreset_n ? _026_ : 1'h1;
  always @(posedge hclk)
    hresp_reg <= _029_;
  assign _029_ = hreset_n ? _028_ : 1'h0;
  always @(posedge hclk)
    be_reg <= _031_;
  assign _031_ = hreset_n ? _030_ : 4'h0;
  always @(posedge hclk)
    wdata_reg <= _033_;
  assign _033_ = hreset_n ? _032_ : 32'd0;
  always @(posedge hclk)
    addr_reg <= _035_;
  assign _035_ = hreset_n ? _034_ : 16'h0000;
  always @(posedge hclk)
    we_reg <= _037_;
  assign _037_ = hreset_n ? _036_ : 1'h0;
  always @(posedge hclk)
    access_itcm <= _039_;
  assign _039_ = hreset_n ? _038_ : 1'h0;
  assign itcm_addr_o = access_itcm ? addr_reg : 16'h0000;
  assign itcm_be_o = access_itcm ? be_reg : 4'h0;
  assign dtcm_addr_o = _013_ ? addr_reg : 16'h0000;
  assign dtcm_be_o = _013_ ? be_reg : 4'h0;
  assign hrdata_aligned = hrdata;
  assign word_addr = haddr[16:1];
  assign byte_addr = haddr[16:0];
  assign dtcm_wdata_o = wdata_reg;
  assign itcm_wdata_o = wdata_reg;
  assign hresp = hresp_reg;
  assign hready = hready_reg;
endmodule

module uart_simple(pclk, preset_n, psel, penable, pwrite, paddr, pwdata, pready, prdata, pslverr, rx, tx, irq);
  input pclk;
  wire pclk;
  input preset_n;
  wire preset_n;
  input psel;
  wire psel;
  input penable;
  wire penable;
  input pwrite;
  wire pwrite;
  input [31:0] paddr;
  wire [31:0] paddr;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  output pready;
  reg pready;
  output [31:0] prdata;
  reg [31:0] prdata;
  output pslverr;
  wire pslverr;
  input rx;
  wire rx;
  output tx;
  reg tx;
  output irq;
  wire irq;
  wire [31:0] _000_;
  wire [31:0] _001_;
  wire [31:0] _002_;
  wire [3:0] _003_;
  wire [7:0] _004_;
  wire [31:0] _005_;
  wire _006_;
  wire _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [31:0] _010_;
  wire [3:0] _011_;
  wire [7:0] _012_;
  wire _013_;
  wire [31:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire [0:0] _022_;
  wire [0:0] _023_;
  wire [31:0] _024_;
  wire [31:0] _025_;
  wire [0:0] _026_;
  wire [0:0] _027_;
  wire [3:0] _028_;
  wire [3:0] _029_;
  wire [7:0] _030_;
  wire [7:0] _031_;
  wire [31:0] _032_;
  wire [31:0] _033_;
  wire [0:0] _034_;
  wire [0:0] _035_;
  wire [7:0] _036_;
  wire _037_;
  wire _038_;
  wire [31:0] _039_;
  wire [31:0] _040_;
  wire _041_;
  wire _042_;
  wire [7:0] _043_;
  wire _044_;
  wire [7:0] _045_;
  wire [7:0] _046_;
  wire [3:0] _047_;
  wire [3:0] _048_;
  wire [3:0] _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire [31:0] _053_;
  wire _054_;
  wire [31:0] _055_;
  wire [31:0] _056_;
  wire [31:0] _057_;
  wire _058_;
  wire [31:0] _059_;
  wire [31:0] _060_;
  wire [31:0] _061_;
  wire [31:0] _062_;
  wire [31:0] _063_;
  wire [31:0] _064_;
  wire [31:0] _065_;
  wire [31:0] _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire [31:0] _071_;
  wire _072_;
  wire [31:0] _073_;
  wire [31:0] _074_;
  wire [3:0] _075_;
  reg [31:0] brr_reg;
  reg [31:0] cr_reg;
  reg [31:0] dr_reg;
  reg [31:0] sr_reg;
  reg [3:0] tx_bit_cnt;
  reg tx_busy;
  reg [7:0] tx_shift_reg;
  assign _008_ = preset_n ? _002_ : dr_reg;
  assign _009_ = preset_n ? _001_ : cr_reg;
  assign _010_ = preset_n ? _000_ : brr_reg;
  assign _011_ = preset_n ? _003_ : tx_bit_cnt;
  assign _012_ = preset_n ? _004_ : tx_shift_reg;
  assign _013_ = preset_n ? _006_ : tx;
  assign _014_ = preset_n ? _005_ : sr_reg;
  assign _015_ = preset_n ? _007_ : tx_busy;
  assign _016_ = tx_bit_cnt == 4'h1;
  assign _017_ = tx_bit_cnt > 4'h1;
  assign _018_ = psel && _020_;
  assign _019_ = penable && _021_;
  assign _020_ = ! penable;
  assign _021_ = ! pready;
  always @(posedge pclk)
    dr_reg <= _008_;
  always @(posedge pclk)
    cr_reg <= _009_;
  always @(posedge pclk)
    brr_reg <= _010_;
  always @(posedge pclk)
    tx_bit_cnt <= _011_;
  always @(posedge pclk)
    tx_shift_reg <= _012_;
  always @(posedge pclk)
    tx <= _013_;
  always @(posedge pclk)
    sr_reg <= _014_;
  always @(posedge pclk)
    tx_busy <= _015_;
  assign _036_ = _017_ ? { 1'h0, tx_shift_reg[7:1] } : tx_shift_reg;
  assign _030_ = tx_busy ? _036_ : tx_shift_reg;
  assign _028_ = tx_busy ? _075_ : tx_bit_cnt;
  assign _037_ = _016_ ? 1'h1 : 1'h0;
  assign _038_ = _017_ ? 1'h1 : _037_;
  assign _007_ = tx_busy ? _038_ : 1'h0;
  assign _039_ = _016_ ? sr_reg : { sr_reg[31:7], 1'h1, sr_reg[5:0] };
  assign _040_ = _017_ ? sr_reg : _039_;
  assign _005_ = tx_busy ? _040_ : sr_reg;
  assign _041_ = _016_ ? 1'h1 : tx;
  assign _042_ = _017_ ? tx_shift_reg[0] : _041_;
  assign _006_ = tx_busy ? _042_ : tx;
  assign _043_ = _044_ ? pwdata[7:0] : tx_shift_reg;
  assign _045_ = pwrite ? _043_ : tx_shift_reg;
  assign _046_ = _019_ ? _045_ : tx_shift_reg;
  assign _004_ = _018_ ? tx_shift_reg : _046_;
  assign _047_ = _044_ ? 4'ha : tx_bit_cnt;
  assign _048_ = pwrite ? _047_ : tx_bit_cnt;
  assign _049_ = _019_ ? _048_ : tx_bit_cnt;
  assign _003_ = _018_ ? tx_bit_cnt : _049_;
  assign _050_ = _044_ ? 1'h1 : tx_busy;
  assign _051_ = pwrite ? _050_ : tx_busy;
  assign _052_ = _019_ ? _051_ : tx_busy;
  assign _026_ = _018_ ? tx_busy : _052_;
  assign _053_ = _054_ ? pwdata : brr_reg;
  assign _055_ = pwrite ? _053_ : brr_reg;
  assign _056_ = _019_ ? _055_ : brr_reg;
  assign _000_ = _018_ ? brr_reg : _056_;
  assign _057_ = _058_ ? pwdata : cr_reg;
  assign _059_ = pwrite ? _057_ : cr_reg;
  assign _060_ = _019_ ? _059_ : cr_reg;
  assign _001_ = _018_ ? cr_reg : _060_;
  assign _061_ = _044_ ? { sr_reg[31:7], 1'h0, sr_reg[5:0] } : sr_reg;
  assign _062_ = pwrite ? _061_ : sr_reg;
  assign _063_ = _019_ ? _062_ : sr_reg;
  assign _024_ = _018_ ? sr_reg : _063_;
  assign _064_ = _044_ ? { 24'h000000, pwdata[7:0] } : dr_reg;
  assign _065_ = pwrite ? _064_ : dr_reg;
  assign _066_ = _019_ ? _065_ : dr_reg;
  assign _002_ = _018_ ? dr_reg : _066_;
  assign _067_ = _044_ ? 1'h0 : tx;
  assign _068_ = pwrite ? _067_ : tx;
  assign _069_ = _019_ ? _068_ : tx;
  assign _022_ = _018_ ? tx : _069_;
  assign _070_ = _019_ ? 1'h1 : pready;
  assign _034_ = _018_ ? 1'h0 : _070_;
  function [31:0] _144_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _144_ = b[31:0];
      4'b??1?:
        _144_ = b[63:32];
      4'b?1??:
        _144_ = b[95:64];
      4'b1???:
        _144_ = b[127:96];
      default:
        _144_ = a;
    endcase
  endfunction
  assign _071_ = _144_(32'd0, { dr_reg, sr_reg, cr_reg, brr_reg }, { _044_, _072_, _058_, _054_ });
  assign _054_ = paddr[7:2] == 6'h03;
  assign _058_ = paddr[7:2] == 6'h02;
  assign _072_ = paddr[7:2] == 6'h01;
  assign _044_ = ! paddr[7:2];
  assign _073_ = pwrite ? prdata : _071_;
  assign _074_ = _019_ ? _073_ : prdata;
  assign _032_ = _018_ ? prdata : _074_;
  assign _075_ = tx_bit_cnt - 1'h1;
  always @(posedge pclk)
    tx <= _023_;
  assign _023_ = preset_n ? _022_ : 1'h1;
  always @(posedge pclk)
    sr_reg <= _025_;
  assign _025_ = preset_n ? _024_ : 32'd64;
  always @(posedge pclk)
    tx_busy <= _027_;
  assign _027_ = preset_n ? _026_ : 1'h0;
  always @(posedge pclk)
    tx_bit_cnt <= _029_;
  assign _029_ = preset_n ? _028_ : 4'h0;
  always @(posedge pclk)
    tx_shift_reg <= _031_;
  assign _031_ = preset_n ? _030_ : 8'h00;
  always @(posedge pclk)
    prdata <= _033_;
  assign _033_ = preset_n ? _032_ : 32'd0;
  always @(posedge pclk)
    pready <= _035_;
  assign _035_ = preset_n ? _034_ : 1'h0;
  assign irq = 1'h0;
  assign pslverr = 1'h0;
endmodule
